// <auto-generated />
using System;
using LogisticsApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogisticsApi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LogisticsApi.Models.Entities.AuditLog", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uniqueidentifier").HasDefaultValueSql("NEWSEQUENTIALID()");
                b.Property<string>("Action").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("EntityId").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("EntityType").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("IpAddress").HasColumnType("nvarchar(max)");
                b.Property<string>("NewValues").HasColumnType("nvarchar(max)");
                b.Property<string>("Notes").HasColumnType("nvarchar(max)");
                b.Property<string>("OldValues").HasColumnType("nvarchar(max)");
                b.Property<DateTime>("Timestamp").HasColumnType("datetime2").HasDefaultValueSql("GETUTCDATE()");
                b.Property<string>("UserEmail").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("UserId").IsRequired().HasColumnType("nvarchar(max)");
                b.HasKey("Id");
                b.ToTable("AuditLogs");
            });

            modelBuilder.Entity("LogisticsApi.Models.Entities.Assignment", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uniqueidentifier").HasDefaultValueSql("NEWSEQUENTIALID()");
                b.Property<DateTime?>("ActualEndTime").HasColumnType("datetime2");
                b.Property<Guid>("AssignedById").HasColumnType("uniqueidentifier");
                b.Property<string>("AssignmentType").IsRequired().HasMaxLength(10).HasColumnType("nvarchar(10)").HasDefaultValue("Auto");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2").HasDefaultValueSql("GETUTCDATE()");
                b.Property<Guid>("DriverId").HasColumnType("uniqueidentifier");
                b.Property<DateTime?>("EstimatedEndTime").HasColumnType("datetime2");
                b.Property<string>("Notes").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<DateTime>("StartTime").HasColumnType("datetime2");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)").HasDefaultValue("Active");
                b.Property<Guid>("TripRequestId").HasColumnType("uniqueidentifier");
                b.Property<Guid>("VehicleId").HasColumnType("uniqueidentifier");
                b.HasKey("Id");
                b.HasIndex("AssignedById");
                b.HasIndex("DriverId");
                b.HasIndex("TripRequestId").IsUnique();
                b.HasIndex("VehicleId");
                b.ToTable("Assignments");
            });

            modelBuilder.Entity("LogisticsApi.Models.Entities.FuelLog", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uniqueidentifier").HasDefaultValueSql("NEWSEQUENTIALID()");
                b.Property<decimal>("CostPerLitre").HasColumnType("decimal(8,4)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2").HasDefaultValueSql("GETUTCDATE()");
                b.Property<DateOnly>("FuelDate").HasColumnType("date");
                b.Property<decimal>("LitresFilled").HasColumnType("decimal(8,2)");
                b.Property<Guid>("LoggedById").HasColumnType("uniqueidentifier");
                b.Property<string>("Notes").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<int>("OdometerAtFill").HasColumnType("int");
                b.Property<string>("ReceiptBlobUrl").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<string>("StationName").HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<decimal>("TotalCost").HasColumnType("decimal(10,2)");
                b.Property<Guid>("VehicleId").HasColumnType("uniqueidentifier");
                b.HasKey("Id");
                b.HasIndex("LoggedById");
                b.HasIndex("VehicleId");
                b.ToTable("FuelLogs");
            });

            modelBuilder.Entity("LogisticsApi.Models.Entities.MaintenanceRecord", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uniqueidentifier").HasDefaultValueSql("NEWSEQUENTIALID()");
                b.Property<string>("AttachmentBlobUrl").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<DateOnly?>("CompletedDate").HasColumnType("date");
                b.Property<decimal?>("Cost").HasColumnType("decimal(10,2)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2").HasDefaultValueSql("GETUTCDATE()");
                b.Property<string>("Notes").HasMaxLength(1000).HasColumnType("nvarchar(1000)");
                b.Property<DateOnly>("ScheduledDate").HasColumnType("date");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)").HasDefaultValue("Scheduled");
                b.Property<string>("Type").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2").HasDefaultValueSql("GETUTCDATE()");
                b.Property<string>("VendorContact").HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("VendorName").HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<Guid>("VehicleId").HasColumnType("uniqueidentifier");
                b.HasKey("Id");
                b.HasIndex("VehicleId");
                b.ToTable("MaintenanceRecords");
            });

            modelBuilder.Entity("LogisticsApi.Models.Entities.Notification", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uniqueidentifier").HasDefaultValueSql("NEWSEQUENTIALID()");
                b.Property<string>("Body").IsRequired().HasMaxLength(2000).HasColumnType("nvarchar(2000)");
                b.Property<string>("Channel").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)").HasDefaultValue("InApp");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2").HasDefaultValueSql("GETUTCDATE()");
                b.Property<bool>("IsRead").HasColumnType("bit");
                b.Property<string>("RelatedEntityId").HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("RelatedEntityType").HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<Guid>("RecipientId").HasColumnType("uniqueidentifier");
                b.Property<DateTime?>("SentAt").HasColumnType("datetime2");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)").HasDefaultValue("Pending");
                b.Property<string>("Subject").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("Type").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.HasKey("Id");
                b.HasIndex("RecipientId");
                b.ToTable("Notifications");
            });

            modelBuilder.Entity("LogisticsApi.Models.Entities.TripRequest", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uniqueidentifier").HasDefaultValueSql("NEWSEQUENTIALID()");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2").HasDefaultValueSql("GETUTCDATE()");
                b.Property<string>("DestinationLocation").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("Notes").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<string>("PickupLocation").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("Priority").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)").HasDefaultValue("Normal");
                b.Property<string>("Purpose").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<DateTime>("RequestedDateTime").HasColumnType("datetime2");
                b.Property<Guid>("RequestedById").HasColumnType("uniqueidentifier");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)").HasDefaultValue("Pending");
                b.HasKey("Id");
                b.HasIndex("RequestedById");
                b.ToTable("TripRequests");
            });

            modelBuilder.Entity("LogisticsApi.Models.Entities.User", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uniqueidentifier").HasDefaultValueSql("NEWSEQUENTIALID()");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2").HasDefaultValueSql("GETUTCDATE()");
                b.Property<string>("DriverStatus").HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<string>("Email").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
                b.Property<string>("EntraObjectId").IsRequired().HasMaxLength(36).HasColumnType("nvarchar(36)");
                b.Property<string>("FullName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<DateOnly?>("LicenceExpiry").HasColumnType("date");
                b.Property<string>("LicenceNo").HasMaxLength(30).HasColumnType("nvarchar(30)");
                b.Property<DateTime?>("LastStatusChange").HasColumnType("datetime2");
                b.Property<string>("PhoneNumber").HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<string>("Role").IsRequired().HasMaxLength(30).HasColumnType("nvarchar(30)");
                b.HasKey("Id");
                b.HasIndex("Email").IsUnique().HasFilter("[Email] IS NOT NULL AND [Email] <> ''");
                b.HasIndex("EntraObjectId").IsUnique();
                b.ToTable("Users");
            });

            modelBuilder.Entity("LogisticsApi.Models.Entities.Vehicle", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uniqueidentifier").HasDefaultValueSql("NEWSEQUENTIALID()");
                b.Property<Guid?>("AssignedMechanicId").HasColumnType("uniqueidentifier");
                b.Property<string>("AssetTagNo").HasMaxLength(40).HasColumnType("nvarchar(40)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2").HasDefaultValueSql("GETUTCDATE()");
                b.Property<string>("FuelType").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)").HasDefaultValue("Diesel");
                b.Property<DateOnly?>("LastServiceDate").HasColumnType("date");
                b.Property<string>("Make").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("Model").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<DateOnly?>("NextServiceDate").HasColumnType("date");
                b.Property<int>("OdometerKm").HasColumnType("int");
                b.Property<int?>("MileageAtPurchase").HasColumnType("int");
                b.Property<int?>("PreviousMileageAtPurchase").HasColumnType("int");
                b.Property<string>("RegistrationNo").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<int>("ServiceIntervalKm").HasColumnType("int");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)").HasDefaultValue("Available");
                b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2").HasDefaultValueSql("GETUTCDATE()");
                b.Property<short>("Year").HasColumnType("smallint");
                b.HasKey("Id");
                b.HasIndex("AssetTagNo");
                b.HasIndex("AssignedMechanicId");
                b.HasIndex("RegistrationNo").IsUnique();
                b.ToTable("Vehicles");
            });

            // Configure relationships
            modelBuilder.Entity("LogisticsApi.Models.Entities.Assignment", b =>
            {
                b.HasOne("LogisticsApi.Models.Entities.User", "AssignedBy").WithMany("AssignmentsCreated").HasForeignKey("AssignedById").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.HasOne("LogisticsApi.Models.Entities.User", "Driver").WithMany("AssignmentsAsDriver").HasForeignKey("DriverId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.HasOne("LogisticsApi.Models.Entities.TripRequest", "TripRequest").WithOne("Assignment").HasForeignKey("LogisticsApi.Models.Entities.Assignment", "TripRequestId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.HasOne("LogisticsApi.Models.Entities.Vehicle", "Vehicle").WithMany("Assignments").HasForeignKey("VehicleId").OnDelete(DeleteBehavior.Restrict).IsRequired();
            });

            modelBuilder.Entity("LogisticsApi.Models.Entities.FuelLog", b =>
            {
                b.HasOne("LogisticsApi.Models.Entities.User", "LoggedBy").WithMany("FuelLogs").HasForeignKey("LoggedById").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.HasOne("LogisticsApi.Models.Entities.Vehicle", "Vehicle").WithMany("FuelLogs").HasForeignKey("VehicleId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            });

            modelBuilder.Entity("LogisticsApi.Models.Entities.MaintenanceRecord", b =>
            {
                b.HasOne("LogisticsApi.Models.Entities.Vehicle", "Vehicle").WithMany("MaintenanceRecords").HasForeignKey("VehicleId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            });

            modelBuilder.Entity("LogisticsApi.Models.Entities.Notification", b =>
            {
                b.HasOne("LogisticsApi.Models.Entities.User", "Recipient").WithMany("Notifications").HasForeignKey("RecipientId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            });

            modelBuilder.Entity("LogisticsApi.Models.Entities.TripRequest", b =>
            {
                b.HasOne("LogisticsApi.Models.Entities.User", "RequestedBy").WithMany().HasForeignKey("RequestedById").OnDelete(DeleteBehavior.Restrict).IsRequired();
            });

            modelBuilder.Entity("LogisticsApi.Models.Entities.Vehicle", b =>
            {
                b.HasOne("LogisticsApi.Models.Entities.User", "AssignedMechanic").WithMany().HasForeignKey("AssignedMechanicId").OnDelete(DeleteBehavior.SetNull);
            });
#pragma warning restore 612, 618
        }
    }
}
